[build]
  command = "npm run build"  # Build command for the app
  publish = "dist"           # Directory where the built files are stored

[context.production.environment]
  NODE_VERSION = "16"        # Specify the correct Node version

