
[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "16"  # Make sure to use the correct version

[[plugins]]
  package = "@netlify/plugin-node-versions"
  version = "2.0.0"
